bot:
  name: qqqMaoBot
  token: 7190126740:AAFdTc28e4MszuZu0_fHegMndUfC-J3q2Mc
  uri:  https://f0e1-185-122-29-71.ngrok-free.app

server:
  port: 8084
  ssl:
    enabled:
      false

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: userok
    password: p@ssw0rd
    queues:
      text-message-update: text_message_update
      doc-message-update: doc_message_update
      photo-message-update: photo_message_update
      answer-message: answer_message