server:
  port: 8087

spring:
  mail:
    host: smtp.mail.ru
    port: 465
    protocol: smtps
    username: qqmaobot@mail.ru
    password: b0XinzG6qwCnrGcb1NaF
  rabbitmq:
    host: localhost
    port: 5672
    username: userok
    password: p@ssw0rd
    queues:
      registration-mail: registration_mail


service:
  activation:
    uri: http://127.0.0.1:8086/user/activation?id={id}
